### ISSUE TITLE
padding screws up placeholder text on firefox

### ISSUE THREAD

**Issue by hayksaakian** [TimIsOverpowered/AngelThump#3]
![screen shot 2016-08-06 at 9 53 27 pm](https://cloud.githubusercontent.com/assets/1884787/17460541/527ea304-5c20-11e6-9338-e30fd2781dd5.png)
![screen shot 2016-08-06 at 9 53 23 pm](https://cloud.githubusercontent.com/assets/1884787/17460542/5281ad56-5c20-11e6-9b2f-638f9e55658a.png)

**Comment by TimIsOverpowered** [comment]
its not padding, its a security error with firefox

**Comment by TimIsOverpowered** [comment]
fixed padding
