### ISSUE TITLE
healthcheck memes

### ISSUE THREAD

**Issue by TimIsOverpowered** [TimIsOverpowered/AngelThump#37]

**Comment by OneTrooper** [comment]
Is there any way for me to test my connection to the ingest servers? I'm still having 40% frame drop problems while streaming to Angelthump exclusively.

**Comment by TimIsOverpowered** [comment]
http://speedtest-nyc3.digitalocean.com/

**Comment by OneTrooper** [comment]
I get 944.24 Mb/s down and 19.41 MB/s up for NYC3. Strangely, I get 335.33 down but 210.45 up for NYC2 and similarly with NYC1 I get 472.47 U / 208.47 D. Is your server specifically NYC3? When I stream my connection bounces heavily between 1300 and 4000 kb/s leaving me with 40-50% frames dropped.

**Comment by TimIsOverpowered** [comment]
it is indeed nyc3.

**Comment by OneTrooper** [comment]
Is there any way for me to figure out why my upload to NYC3 is significantly worse than the others? 19.41 Mb/s should be fine for 3500 bitrate anyway right?

**Comment by TimIsOverpowered** [comment]
healthcheck memes live using netdata && status page is live at https://status.angelthump.com
