### ISSUE TITLE
Chromecasting doesn't work

### ISSUE THREAD

**Issue by Mikecom32** [TimIsOverpowered/AngelThump#42]
Chromecasting from Angelthump doesn't work, although the embedded player does support it and the button is there. Here's what's going on in the console (pulled from Chrome dev tools):

```
VIDEOJS: Cast video: https://nyc-hub.angelthump.com:6969/hls/shawarmafury/index.m3u8
VIDEOJS: Session initialized: 098d3724-9d8e-420a-afb9-0258c8610b5f source : https://nyc-hub.angelthump.com:6969/hls/shawarmafury/index.m3u8 type : application/x-mpegURL 
VIDEOJS: Cast Error: {"code":"session_error","description":"LOAD_FAILED","details":{"type":"LOAD_FAILED"}}
```
From what I can tell, it looks like the issue is caused by CORS. [Here is the Google documentation on chromecast requirements](https://developers.google.com/cast/docs/player) that lists the CORS requirement, along with a link to some example configurations for pretty much every popular webserver.

**Comment by TimIsOverpowered** [comment]
should be fixed
