### ISSUE TITLE
Fix HTTPS

### ISSUE THREAD

**Issue by TimIsOverpowered** [TimIsOverpowered/AngelThump#5]
Each edge server is running under http instead of https. By default, every browser blocks MIXED CONTENT (HTTPS to http).

Will have to make each nginx edge server https unless there is a better solution to this.

**Comment by TimIsOverpowered** [comment]
LetsEncrypt doesn't allow wildcard certificates

**Comment by KenanY** [comment]
How many servers are there?

**Comment by TimIsOverpowered** [comment]
The problem isn't about how many. The problem is if I add more servers to scale up for events.

**Comment by TimIsOverpowered** [comment]
done

https://github.com/TimIsOverpowered/AngelThump/commit/7802fc03f36b897f936f6d92a41947022baea5a9
